const TOKEN_NAME_CONTROL_IF: string = '$CONTROL_IF_TOKEN_____';
const TOKEN_NAME_CONTROL_ELSEIF: string = '$CONTROL_ELSEIF_TOKEN_____';
const TOKEN_NAME_CONTROL_ELSE: string = '$CONTROL_ELSE_TOKEN_____';
const TOKEN_NAME_CONTROL_ENDIF: string = '$CONTROL_ENDIF_TOKEN_____';
const TOKEN_NAME_CONTROL_FOR: string = '$CONTROL_FORSTART_TOKEN_____';
const TOKEN_NAME_CONTROL_ENDFOR: string = '$CONTROL_ENDFOR_TOKEN_____';
const TOKEN_NAME_CONTROL_IMPORT: string = '$CONTROL_IMPORT_TOKEN';
const TOKEN_NAME_CONTROL_COMPONENT: string = '$CONTROL_COMPONENT_TOKEN_____';
const TOKEN_NAME_CONTROL_PROPS: string = '$CONTROL_PROPS_TOKEN_____';
export const CONTROL_TOKEN_NAMES_MAP: { [key: string]: string } = {
    IF: TOKEN_NAME_CONTROL_IF,
    ELSEIF: TOKEN_NAME_CONTROL_ELSEIF,
    ELSE: TOKEN_NAME_CONTROL_ELSE,
    ENDIF: TOKEN_NAME_CONTROL_ENDIF,
    FOR: TOKEN_NAME_CONTROL_FOR,
    ENDFOR: TOKEN_NAME_CONTROL_ENDFOR,
    IMPORT: TOKEN_NAME_CONTROL_IMPORT,
    COMPONENT: TOKEN_NAME_CONTROL_COMPONENT,
    PROPS: TOKEN_NAME_CONTROL_PROPS
}