export const _TYPE_BLANK_TOKEN: string = '$BLANK_TOKEN_____';
export const _TYPE_BAD_TOKEN: string = '$BAD_TOKEN_____';
export const _TYPE_INVALID_INPUT: string = '$INVALID_INPUT_____';
export const _TYPE_EOF_TOKEN: string = '$EOF_TOKEN_____';
export const _TYPE_WHITESPACE_TOKEN: string = '$WHITESPACE_TOKEN_____';
export const _TYPE_HTML_TOKEN: string = '$HTML_TOKEN_____';
export const _TYPE_INJECTION_TOKEN: string = '$INJECT_TOKEN_____';
export const _TYPE_CONTENT_TOKEN: string = '$CONTENT_TOKEN_____';
export const _TYPE_CONTROL_GENERIC_TOKEN: string = '$CONTROL_GENERIC_TOKEN_____';
export const _TYPE_CONTROL_IF_TOKEN: string = '$CONTROL_TYPE_IF_TOKEN_____';
export const _TYPE_CONTROL_FOR_TOKEN: string = '$CONTROL_TYPE_FOR_TOKEN_____';
export const _TYPE_CONTROL_IMPORT_TOKEN: string = '$CONTROL_TYPE_IMPORT_TOKEN_____';
export const _TYPE_CONTROL_COMPONENT_TOKEN: string = '$CONTROL_TYPE_CONTROL_TOKEN_____';
export const _TYPE_CONTROL_PROPS_TOKEN: string = '$CONTROL_TYPE_PROPS_TOKEN_____';
export const CONTROLIF_IF_TOKEN: string = '$CONTROL_IF_TOKEN_____';
export const CONTROLIF_ELSEIF_TOKEN: string = '$CONTROL_ELSEIF_TOKEN_____';
export const CONTROLIF_ELSE_TOKEN: string = '$CONTROL_ELSE_TOKEN_____';
export const CONTROLIF_ENDIF_TOKEN: string = '$CONTROL_ENDIF_TOKEN_____';
export const CONTROLFOR_FOR_TOKEN: string = '$CONTROL_FORSTART_TOKEN_____';
export const CONTROLFOR_ENDFOR_TOKEN: string = '$CONTROL_ENDFOR_TOKEN_____';
export const CONTROL_IMPORT_TOKEN: string = '$CONTROL_IMPORT_TOKEN';
export const CONTROL_TOKEN_SUFFIX: string = '$CONTROL_';
export const CONTROL_COMPONENT_TOKEN: string = '$CONTROL_COMPONENT_TOKEN_____';
export const CONTROL_PROPS_TOKEN: string = '$CONTROL_PROPS_TOKEN_____';


export const _ALL_TOKEN_TYPES: Array<string> = [
    _TYPE_BLANK_TOKEN
    , _TYPE_BAD_TOKEN
    , _TYPE_INVALID_INPUT
    , _TYPE_EOF_TOKEN
    , _TYPE_WHITESPACE_TOKEN
    , _TYPE_HTML_TOKEN
    , _TYPE_INJECTION_TOKEN
    , _TYPE_CONTENT_TOKEN
    , _TYPE_CONTROL_GENERIC_TOKEN
    , _TYPE_CONTROL_IF_TOKEN
    , _TYPE_CONTROL_FOR_TOKEN
    , _TYPE_CONTROL_IMPORT_TOKEN
    , _TYPE_CONTROL_COMPONENT_TOKEN
    , _TYPE_CONTROL_PROPS_TOKEN
];

export const _SUPPORTED_TOKE_TYPES: Array<string> = [ 
    _TYPE_HTML_TOKEN
    , _TYPE_CONTROL_GENERIC_TOKEN
    , _TYPE_INJECTION_TOKEN
    , _TYPE_CONTENT_TOKEN
    , _TYPE_CONTROL_IMPORT_TOKEN

 ];

export const _ALL_CONTROL_TOKEN_NAMES: Array<string> = [
    , CONTROLIF_IF_TOKEN
    , CONTROLIF_ELSEIF_TOKEN
    , CONTROLIF_ELSE_TOKEN
    , CONTROLIF_ENDIF_TOKEN
    , CONTROLFOR_FOR_TOKEN
    , CONTROLFOR_ENDFOR_TOKEN
    , CONTROL_IMPORT_TOKEN
] as Array<string>;

export const _CONTROL_NAME_MAP: {[key: string]: string} = {
    _CONTROLIF_IF_TOKEN: CONTROLIF_ENDIF_TOKEN,
    _CONTROLIF_ELSEIF_TOKEN: CONTROLIF_ENDIF_TOKEN,
    _CONTROLIF_ELSE_TOKEN: CONTROLIF_ENDIF_TOKEN,
    _CONTROLFOR_FOR_TOKEN: CONTROLFOR_ENDFOR_TOKEN,
    _CONTROL_IMPORT_TOKEN: CONTROL_IMPORT_TOKEN
}